import Easing, { EasingFunction } from 'easing-functions';

export const enum CurveFunction {
  BEZIER = 'BEZIER',
  LINEAR = 'LINEAR',
  QUADRATIC_IN = 'QUADRATIC_IN',
  QUADRATIC_OUT = 'QUADRATIC_OUT',
  QUADRATIC_IN_OUT = 'QUADRATIC_IN_OUT',
  CUBIC_IN = 'CUBIC_IN',
  CUBIC_OUT = 'CUBIC_OUT',
  CUBIC_IN_OUT = 'CUBIC_IN_OUT',
  QUARTIC_IN = 'QUARTIC_IN',
  QUARTIC_OUT = 'QUARTIC_OUT',
  QUARTIC_IN_OUT = 'QUARTIC_IN_OUT',
  QUINTIC_IN = 'QUINTIC_IN',
  QUINTIC_OUT = 'QUINTIC_OUT',
  QUINTIC_IN_OUT = 'QUINTIC_IN_OUT',
  SINUSOIDAL_IN = 'SINUSOIDAL_IN',
  SINUSOIDAL_OUT = 'SINUSOIDAL_OUT',
  SINUSOIDAL_IN_OUT = 'SINUSOIDAL_IN_OUT',
  EXPONENTIAL_IN = 'EXPONENTIAL_IN',
  EXPONENTIAL_OUT = 'EXPONENTIAL_OUT',
  EXPONENTIAL_IN_OUT = 'EXPONENTIAL_IN_OUT',
  CIRCULAR_IN = 'CIRCULAR_IN',
  CIRCULAR_OUT = 'CIRCULAR_OUT',
  CIRCULAR_IN_OUT = 'CIRCULAR_IN_OUT',
  ELASTIC_IN = 'ELASTIC_IN',
  ELASTIC_OUT = 'ELASTIC_OUT',
  ELASTIC_IN_OUT = 'ELASTIC_IN_OUT',
  BACK_IN = 'BACK_IN',
  BACK_OUT = 'BACK_OUT',
  BACK_IN_OUT = 'BACK_IN_OUT',
  BOUNCE_IN = 'BOUNCE_IN',
  BOUNCE_OUT = 'BOUNCE_OUT',
  BOUNCE_IN_OUT = 'BOUNCE_IN_OUT',
}

const CurveFunctionMap: Partial<Record<CurveFunction, EasingFunction>> = {
  [CurveFunction.LINEAR]: Easing.Linear.None,
  [CurveFunction.QUADRATIC_IN]: Easing.Quadratic.In,
  [CurveFunction.QUADRATIC_OUT]: Easing.Quadratic.Out,
  [CurveFunction.QUADRATIC_IN_OUT]: Easing.Quadratic.InOut,
  [CurveFunction.CUBIC_IN]: Easing.Cubic.In,
  [CurveFunction.CUBIC_OUT]: Easing.Cubic.Out,
  [CurveFunction.CUBIC_IN_OUT]: Easing.Cubic.InOut,
  [CurveFunction.QUARTIC_IN]: Easing.Quartic.In,
  [CurveFunction.QUARTIC_OUT]: Easing.Quartic.Out,
  [CurveFunction.QUARTIC_IN_OUT]: Easing.Quartic.InOut,
  [CurveFunction.QUINTIC_IN]: Easing.Quintic.In,
  [CurveFunction.QUINTIC_OUT]: Easing.Quintic.Out,
  [CurveFunction.QUINTIC_IN_OUT]: Easing.Quintic.InOut,
  [CurveFunction.SINUSOIDAL_IN]: Easing.Sinusoidal.In,
  [CurveFunction.SINUSOIDAL_OUT]: Easing.Sinusoidal.Out,
  [CurveFunction.SINUSOIDAL_IN_OUT]: Easing.Sinusoidal.InOut,
  [CurveFunction.EXPONENTIAL_IN]: Easing.Exponential.In,
  [CurveFunction.EXPONENTIAL_OUT]: Easing.Exponential.Out,
  [CurveFunction.EXPONENTIAL_IN_OUT]: Easing.Exponential.InOut,
  [CurveFunction.CIRCULAR_IN]: Easing.Circular.In,
  [CurveFunction.CIRCULAR_OUT]: Easing.Circular.Out,
  [CurveFunction.CIRCULAR_IN_OUT]: Easing.Circular.InOut,
  [CurveFunction.ELASTIC_IN]: Easing.Elastic.In,
  [CurveFunction.ELASTIC_OUT]: Easing.Elastic.Out,
  [CurveFunction.ELASTIC_IN_OUT]: Easing.Elastic.InOut,
  [CurveFunction.BACK_IN]: Easing.Back.In,
  [CurveFunction.BACK_OUT]: Easing.Back.Out,
  [CurveFunction.BACK_IN_OUT]: Easing.Back.InOut,
  [CurveFunction.BOUNCE_IN]: Easing.Bounce.In,
  [CurveFunction.BOUNCE_OUT]: Easing.Bounce.Out,
  [CurveFunction.BOUNCE_IN_OUT]: Easing.Bounce.InOut,
};

export const getCurveFunction = (
  curveFunction: EasingFunction | CurveFunction
) =>
  typeof curveFunction === 'function'
    ? curveFunction
    : CurveFunctionMap[curveFunction];
