name: Run Tests

on:
  push:
    branches:
      - 2.0.0
  pull_request:
    branches:
      - 2.0.0

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
      - run: npm install
      - run: npm run test
