name: Generate and Deploy Typedoc

on:
  push:
    branches:
      - 2.0.0
  pull_request:
    branches:
      - 2.0.0

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Disable Jekyll
        run: echo "" > docs/.nojekyll

      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Generate Typedoc documentation
        run: npx typedoc

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs
